export type Bookmark = {
  title: string
  href: string
}

export const bookmarks: Bookmark[] = [
  { title: "All Demos | Creative Hub | Codrops", href: "https://tympanus.net/codrops/hub/all/" },
  { title: "React Bits — Animated UI Components For React", href: "https://www.reactbits.dev/" },
  { title: "Aceternity UI", href: "https://ui.aceternity.com/" },
  { title: "NexUI — Modern React Component Library", href: "https://nexui-theta.vercel.app/" },
  { title: "ReUI", href: "https://reui.io/" },
  { title: "vibecheck.run", href: "https://www.vibecheck.run/" },
  { title: "Thinking orbs — Animated thinking orb component", href: "https://orbs.jakubantalik.com/" },
  { title: "Amicro — Premium React micro-transitions", href: "https://amicro.vercel.app/" },
  { title: "Colors — Tailwind CSS", href: "https://tailwindcss.com/docs/colors" },
  { title: "Documentation — Tailwind CSS v2", href: "https://v2.tailwindcss.com/docs" },
  { title: "previewed.app 3D editor", href: "https://previewed.app/editor/3D/" },
  { title: "Zigma — Design systems made easy", href: "https://zigma.io/" },
  { title: "Maneken | Catalog", href: "https://editor.maneken.app/" },
  { title: "UX / UI Case Study — Behance", href: "https://www.behance.net/gallery/209476587/UX-UI-Case-Study" },
  { title: "Syncore Rebranding and UI design — Cuberto", href: "https://dribbble.com/shots/25052899-Syncore-Rebranding-and-UI-design" },
  { title: "Pacdora — 3D mockups and dieline templates", href: "https://www.pacdora.com/" },
  { title: "Excalidraw", href: "https://excalidraw.com/" },
  { title: "Beautiful Charts — shadcn/ui", href: "https://ui.shadcn.com/charts" },
  { title: "Chat with the Fluid compute team — Vercel Community", href: "https://vercel.community/t/chat-with-the-fluid-compute-team/6102" },
  { title: "Omma", href: "https://omma.build/jxsvrn80sa" },
  { title: "Visual Electric — AI Image Generator", href: "https://visualelectric.com/" },
  { title: "p5.js Examples", href: "https://p5js.org/examples/#animation%20and%20variables" },
  { title: "Subframe", href: "https://www.subframe.com/" },
  { title: "Twinmotion — Real-time visualization", href: "https://www.twinmotion.com/en-US" },
  { title: "Cursor Directory — Rules & MCP servers", href: "https://cursor.directory/" },
  { title: "Polymet — Idea to prototype", href: "https://www.polymet.ai/" },
  { title: "kit8.net — Graphics assets", href: "https://kit8.net/" },
  { title: "ViewPager — Expo Documentation", href: "https://docs.expo.dev/versions/latest/sdk/view-pager/" },
  { title: "FlatList · React Native", href: "https://reactnative.dev/docs/next/flatlist" },
  { title: "Expo Documentation", href: "https://docs.expo.dev/" },
  { title: "Image Style Props · React Native", href: "https://reactnative.dev/docs/next/image-style-props" },
  { title: "TextInput · React Native Paper", href: "https://callstack.github.io/react-native-paper/4.0/text-input.html" },
  { title: "Nifty Modal Window Effects | Codrops", href: "https://tympanus.net/codrops/2013/06/25/nifty-modal-window-effects/" },
  { title: "Tailwind Carousel — daisyUI", href: "https://daisyui.com/components/carousel/" },
  { title: "Aura — Create beautiful designs", href: "https://aurachat.io/create" },
  { title: "CardSpace (staging) — Supabase", href: "https://supabase.com/dashboard/project/tumtdjvsldzboqxidczx/editor/17273" },
  { title: "21st.dev — The NPM for Design Engineers", href: "https://21st.dev/?tab=components&sort=recommended" },
  { title: "Creative Hub | Codrops", href: "https://tympanus.net/codrops/hub/" },
  { title: "Kibo UI", href: "https://www.kibo-ui.com/" },
  { title: "Drafts · Jitter", href: "https://jitter.video/files/" },
  { title: "StackedAreaChart | Recharts", href: "https://recharts.org/en-US/examples/StackedAreaChart" },
  { title: "Demos Hub | Codrops", href: "https://tympanus.net/codrops/demos/page/2/" },
  { title: "Adobe Photoshop", href: "https://photoshop.adobe.com/id/urn:aaid:sc:EU:5f65dd68-9080-4802-8e7d-f325c547e59e" },
  { title: "Luma Dream Machine | AI Video Generator", href: "https://dream-machine.lumalabs.ai/ideas" },
  { title: "ContentCore", href: "https://contentcore.xyz/" },
  { title: "Kanban — Shadcn.io", href: "https://www.shadcn.io/components/data/kanban" },
  { title: "60fps — UI/UX animation inspiration", href: "https://60fps.design/" },
  { title: "Components | Skiper UI", href: "https://skiper-ui.com/components" },
  { title: "Alert — React Native Reusables", href: "https://reactnativereusables.com/docs/components/alert" },
  { title: "Badge — React Native Reusables", href: "https://reactnativereusables.com/docs/components/badge" },
  { title: "Getting Started | NativeBase", href: "https://docs.nativebase.io/getting-started" },
  { title: "Three.js — JavaScript 3D Library", href: "https://threejs.org/" },
  { title: "Hyper3D — Blue mechanical war suit", href: "https://hyper3d.ai/rodin/e143171b-4702-4ae4-ad96-fcf2a857da42" },
  { title: "AI SDK", href: "https://ai-sdk.dev/" },
  { title: "Foundations: Overview — AI SDK Elements", href: "https://ai-sdk.dev/elements/overview" },
  { title: "Building Blocks for the Web — blocks.so", href: "https://blocks.so/" },
  { title: "Hero Video Dialog | Magic UI", href: "https://magicui.design/docs/components/hero-video-dialog" },
  { title: "AnimatePresence — Motion React", href: "https://motion.dev/docs/react-animate-presence" },
  { title: "beUI — Motion components for React & Next.js", href: "https://beui.dev/" },
  { title: "Border Beam — Animated border beam", href: "https://beam.jakubantalik.com/" },
  { title: "Liquid metal — Animated metal shader", href: "https://metal.jakubantalik.com/" },
  { title: "Landbook — Website design inspiration", href: "https://land-book.com/" },
  { title: "Originkit — Animated component library", href: "https://www.originkit.dev/" },
  { title: "AI Particle Simulator", href: "https://particles.casberry.in/" },
  { title: "Motion examples — React", href: "https://motion.dev/examples?platform=react" },
  { title: "Smooth Tab | KokonutUI", href: "https://kokonutui.com/docs/navigation/smooth-tab" },
  { title: "Scatter Chart | Bklit UI", href: "https://bklit.com/docs/components/scatter-chart" },
  { title: "Chánh Đại — Design Engineer", href: "https://chanhdai.com/" },
  { title: "Animmaster Lib", href: "https://animmasterlib.dev/" },
  { title: "Iconify — Open source icons", href: "https://icon-sets.iconify.design/" },
  { title: "Lineicons", href: "https://lineicons.com/icons" },
  { title: "WebGradients", href: "https://webgradients.com/" },
  { title: "BoardUI — Dashboard UI components", href: "https://www.boardui.com/components" },
  { title: "Inspora", href: "https://www.inspora.design/" },
  { title: "Amicro — Mono charts", href: "https://amicro.vercel.app/mono-charts" },
]

export function bookmarkHost(href: string): string {
  try {
    return new URL(href).host.replace(/^www\./, "")
  } catch {
    return href
  }
}
